name: Test
on:
  push:
    branches:
      - main

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: micha-wehrli/action-test@3d80e2883a4fd65a56bdc1aa00a45366681efc52
